### ISSUE TITLE
Card payment fails on ios

### ISSUE THREAD

**Issue by atmabodhwaw** [FawryPay/Flutter-Fawrypay-Anonymous-sample#4]
<img width="365" alt="image" src="https://github.com/FawryPay/Flutter-Fawrypay-Anonymous-sample/assets/145682556/522ba422-4ce9-4d87-9c79-73a52e8466b0">

**Comment by FWMilad** [comment]
ask the integration to change the configuration for your credentials, this is not code related issue

**Comment by atmabodhwaw** [comment]
This is a fawry sdk error. Utilized both the credentials provided in this example and ours. This functions in android but not in iOS. Seems like you closed this ticket without verifying. Attached is android screenshot. We want to integrate fawry payment system using sdk in our apps that’s wise asking. 
![image](https://github.com/FawryPay/Flutter-Fawrypay-Anonymous-sample/assets/145682556/8c8f290f-a058-4069-8cab-09d50576f433)

**Comment by FWMilad** [comment]
I did validate, and contact the integration team to fix the config for you as the provided screen is not code-related 

make sure you use our latest flutter and latest pod

**Comment by atmabodhwaw** [comment]
Tried with latest example and sdk. Your credential does not open ACS simulator that's why work on iOS. Our try to open and fails on iOS. Simulator require to test failed success transaction.

**Comment by ebrahim2222** [comment]
did you solve it ???

**Comment by FWMilad** [comment]
as mentioned in the previous comment, please contact fawry integration team as your error is related to configuration not code

**Comment by ebrahim2222** [comment]
how ??

**Comment by FWMilad** [comment]
contact your account manager , and check the onboarding email sent to you when you signed the contract with fawry , 

I'm gussing from your questions that you didn't even have a contract or account with fawry , if so ask your employer to contact account manager in fawry

**Comment by FWMilad** [comment]
issue is closed , not technical  issue
